// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	USER_AGENT: "suno/8 CFNetwork/3826.400.120 Darwin/24.3.0";
	SUNO_BASE_URL: "https://studio-api.prod.suno.com";
	CLERK_BASE_URL: "https://clerk.suno.com";
	CLERK_JS_VERSION: "4.70.0";
	CLERK_API_VERSION: "2021-02-05";
	SUNO_COOKIE: string;
	TWOCAPTCHA_API_KEY: string;
	BROWSER: Fetcher;
}
